name: ci

on:
  push:
    branches:
      - "master"
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/ci.yaml'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/ci.yaml'

jobs:
  default:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Sync Python environment
        run: |
          curl -sSf https://rye-up.com/get | bash
          rye sync

      - name: Run fmt check
        run: |
          rye run black . --check
        
      - name: Run lint
        run: |
          rye run mypy .
          rye run ruff .

      - name: Run tests
        run: |
          rye run pytest -v
