# TODO(cnpryer): Eliminate configuration redundancy
name: ci

on:
  push:
    branches:
      - "master"
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/ci.yaml'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/ci.yaml'

jobs:
  Format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Use Cargo to install rye
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install formatting tools
        run: |
          pip install ruff black

      - name: Run fmt
        run: |
          ruff . --select I
          black . --check

  Lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Use Cargo to install rye
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install linting tools
        run: |
          pip install ruff mypy
        
      - name: Run lints
        run: |
          ruff .
          mypy .

  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Use Cargo to install rye
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install testing tools
        run: |
          pip install pytest

      - name: Install project
        run: |
          pip install -e .
        
      - name: Run lints
        run: |
          pytest . -v


